### ISSUE TITLE
Cobigen IDE Installation wrong Java directory

### ISSUE THREAD

**Issue by MikeSchumacherCapgemini** [devonfw/tools-cobigen#1012]
### Expected behavior

When installing via Oomph, after the installation is finished, the .bat files to start the IDE in the workspaces, it should correctly point to the Java version selected in the installer.

### Actual behavior

After creating the workspaces, when trying to start either of `eclipse-cobigen-master.bat` or `eclipse-cobigen-development.bat`, the following error message is shown

![Error_Message(wrong_directory_java_installation)](https://user-images.githubusercontent.com/38068582/65947914-83fa5280-e439-11e9-9d7c-17cf02d7c503.PNG)

The directory it references looks like this.

![Directory(wrong_directory_java_installation)](https://user-images.githubusercontent.com/38068582/65947885-72b14600-e439-11e9-8acb-757ed9818b99.PNG)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Use the Cobigen Oomph installer normally
2.  Use the `clone.bat` in the `workspaces/cobigen-master` directory
3.  Use `create-or-update-workspace.bat` and `update-all-workspaces.bat`
4.  Use `eclipse-cobigen-master.bat` or `eclipse-cobigen-development.bat`

### Affected version:

Latest installer version taken from https://github.com/devonfw/tools-cobigen/wiki/mgmt_ide-setup-oomph#into-an-existing-eclipse-installation

**Comment by MikeSchumacherCapgemini** [comment]
Manually copying the contents of the jdk folder to `Cobigen/IDE/Software/Java` works.

**Comment by jdiazgon** [comment]
```
No java virtual machine was found after searching the following locations:
C:\Users\mischuma\Desktop\CobiGen\IDE/software\java\bin\javaw
```

There is an incorrect slash in `IDE/Software`. It would make sense that correcting that slash fixes the issue. I don't quite understand how "Manually copying the contents of the jdk folder to `Cobigen/IDE/Software/Java`" worked for you.

It would be nice if you can find where exactly the issue is. http://de-mucevolve02/files/oomph/installer/releases/v1.8.0.c-devonfw/ this is the location of the CobiGen oomph installer.

**Comment by jdiazgon** [comment]
If you fix it, I can help you to upload a new version to the server. I had to do it last week 😄

**Comment by MikeSchumacherCapgemini** [comment]
What i mean with manually copying is taking this
![Java_Directory](https://user-images.githubusercontent.com/38068582/65953601-9a59db80-e444-11e9-8f2b-bf096e80452d.PNG)

and copying all of it to the directory above

![Directory](https://user-images.githubusercontent.com/38068582/65953656-bc535e00-e444-11e9-858e-394fbfb05f4e.PNG)

so in the end it looks like this

![Post_Extraction_Directory](https://user-images.githubusercontent.com/38068582/65953607-9ded6280-e444-11e9-8d3e-aca0d5f9a483.PNG)

So the slash is likely not the problem, but rather that it is looking for the directory `\IDE/software\java\bin\javaw` when the directory is `\IDE/software\java\jdk1.8.0_181\bin\javaw`

**Comment by jdiazgon** [comment]
Okaay, got it. Thanks for the explanation!

**Comment by MikeSchumacherCapgemini** [comment]
That is also why i don't know if it is a problem with the instaler necessarily or with a .bat file.
Because the path eclipse is looking for is set in `/scripts/environment-project.bat`, specifically this line `set ECLIPSE_OPT=-vm "%JAVA_HOME%\bin\javaw" -showlocation %WORKSPACE% -vmargs %ECLIPSE_VMARGS%`
So the two options of fixing this are either by extracting the selected java version into the `/software/java` directory or by changing the line in `/scripts/environment-project.bat` to `set ECLIPSE_OPT=-vm "%JAVA_HOME%\SELECTED_JAVA_VERSION\bin\javaw" -showlocation %WORKSPACE% -vmargs %ECLIPSE_VMARGS%`

**Comment by jdiazgon** [comment]
> or by changing the line in /scripts/environment-project.bat to set ECLIPSE_OPT=-vm "%JAVA_HOME%\SELECTED_JAVA_VERSION\bin\javaw"

To me this approach seems cleaner. Though we would need some variable that returns the correct `SELECTED_JAVA_VERSION`. If that is easy, let's go for that approach.

**Comment by maybeec** [comment]
the IDE is constructed to make use of a standard java version to run with. To have multiple java versions in cobigen is basically the problem of trying to support old versions of java as well. For me this is a very special and project specific use case. Anyhow the java version you start your eclipse could be different from the java version you want to develop against.

It's one solution to change the variables-customized.bat to override something, which has been set before, but changing any other script will be problematic during devon-ide scripts update as it will be overwritten automatically. 

Just pointed by @MikeSchumacherCapgemini, I realized, that the latest java version seems to be packed incorrectly on our internal server resulting in a odd naming of the extracted folder. @MikeSchumacherCapgemini  is running a test against the fixed one. Maybe this solves already this issue.

**Comment by MikeSchumacherCapgemini** [comment]
Test was successful, repackaged Java version works now.
