### ISSUE TITLE
cobigen-cli CMD wrappers fail to handle args with quote

### ISSUE THREAD

**Issue by markusschuh** [devonfw/tools-cobigen#1044]
### Expected behavior

As a user, I want to use cobigen-cli in a way so that even arguments containing quotes are handled correctly.

### Actual behavior

cobigen.bat / cg.bat run into an error, when quotes are used in command line call.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

```
...\cobigen.bat g "openapi file.xml"
file.xml""=="" was unexpected at this time.
```

### Comments/Hints:

In order to check in windows CMD, if **any** argument was provided, check only for the first - and avoid to use quotes for that check - or if, then ensure, the quotes in arg are removed.
Instead use **one** of the following examples:

```
IF [%1]==[] . . .
IF #%1==# . . .
IF "%~1"=="" . . .
```

The first is probably the best one. It is listed at https://ss64.com/nt/if.html which is a good reference for developing CMD scripts in my experience.

**Comment by jdiazgon** [comment]
Fixed with #1046

**Comment by markusschuh** [comment]
Your fix may solve the handling of spaces in filenames by java code itself (I have not tested yet) but I had reported an error in the `.bat` calling the java from windows. If you had repeated my "Steps to reproduce" after creating this fix, you should have noticed that the issue still exists. 

I suggest, for debugging purposes only you temporarily remove the "@echo off" at start of `cli\src\main\resources\batchFiles\cobigen.bat` / `cli\src\main\resources\batchFiles\cobigen.bat` (without committing that later ) and then  enter
```
some\path\to\cg.bat "openapi file.txt"
```

This file `openapi file.txt` does not even needs to exist. It is just a sample of a possible file name,. Even when spaces are rarely used, it rarely happens. And support of spaces in file names is not that difficult, if some rules are followed.

CMD is different to any Unix `*sh`: If inside `.bat`/ `.cmd` under windows an argument must contain a space, you can't use single quotes  (you'll run into other errors, since that is not supported for that purpose under CMD and you will end in 2 arguments with unpaired single quotes) 
A user has to use double quotes to quote the space.

And those double quotes will run into an error inside the `.bat` in the line
```
IF "%*"=="" (
```

The java is not even called in this case.  You'll need to change the line inside the `.bat` to
```
IF [%1]==[]  (
```
to make it work. Or you can use one of the other both solution alternatives, I have provided, if you like them more. For example the "mvn.cmd" from maven under windows, uses the 
```
IF "%~1"==  (
```

**Comment by jdiazgon** [comment]
Hi Markus,

my fault. As you said, my colleague implemented the handling of spaces in filenames by java code but we missed that the real issue is on the .bat files. Thanks for pointing this out.
