### ISSUE TITLE
Cleanup oasp4j templates

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#372]
In the crud_angular_client_app part of the oasp4j templates are several empty files.
Please check, whether they can be removed or are faulty.
In addtition the templates.xml contains several `templateExtension` entries without any anttributes than `ref`, which is non sense. Please clean them up as well.

@EastWindShak please do this with priority to have this ready for the release end of the week.

**Comment by jdiazgon** [comment]
I think this issue can be closed, I do not see any empty files or faulty `templateExtensions`
