### ISSUE TITLE
Make CobiGen configuration folder configurable

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#38]
It would be nice to have the ability to configure the current configuration folder for CobiGen. Thus it might be possible that the configuration folder is not even imported as a project into the currently running eclipse. It might be provided by default via SCM.

But this accompanies with a good error handling and user support to guide the user when no folder has been configured or the folder does not exist any more!

**Comment by jdiazgon** [comment]
> it might be possible that the configuration folder is not even imported as a project into the currently running eclipse. 

Already implemented. Now CobiGen downloads templates as a jar and doesn't import them ;)
