### ISSUE TITLE
Check for Docs Header/Footer

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#556]
Compare to devonfw documents. We should have correctly set footer and header of the generated docs from the wiki including the license of the docs.

**Comment by Richter-cg** [comment]
@jdiazgon and me changed https://github.com/devonfw/devonfw-docgen/blob/master/src/main/docbook/xsl/cobigen-pdf.xsl to create the right footnote. I added a commen to the wiki footnote.
