### ISSUE TITLE
Oomph init script for cobigen-eclipse + cobigen-typescript plugin does not work

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#567]
### Expected behavior

After importing automatically all projects in the cobigen-development branch, the projects 
cobigen-eclipse, cobigen-eclipse-test, cobigen-typescriptmerger should be intitialized. **Meaning there are no build plugins and I can directly run tests** within eclipse of these projects.

### Actual behavior

During run of the `maven-init` script, it seems, that the eclipse projects are not build properly. So the two projects keep their build errors after import. In addition, the typescriptplugin build is not running properly. It even hangs on some users machine and does not do anything such that you have to kill eclipse to be able to continue work.

I am not sure why this happens, so part of this issue is to investigate it. Just a **hint: one issue might be the fact, that the maven profiles for building eclipse projects have been changed**. See [deployment section](https://github.com/devonfw/tools-cobigen/wiki/howto_create-a-new-plugin#deployment) for currently valid profiles. E.g. p2Bundle has been replaced by p2-bundle or experimental has been replaced by p2-build-mars,p2-build-experimental -Dp2.upload=experimental
Another potential issue might be the fact, that the process is not running with the correct PATH environment including the login credentials for the nexus. This would then lead to authorized or authenticated failed messages. Please check.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

* create new installation with oomph and clone CobiGen -> development stream
* start cobigen-development eclipse after installation and wait for automatic setup
* wait until everything has been setup and the projects are cloned. Keep the oomph window open 
* see the log of the oomph init setup. Three projects as mentioned above should have been initialized but the build always fails.

**Comment by jdiazgon** [comment]
Closing as it is already fixed
