### ISSUE TITLE
Cyclic dependency in OpenAPI.yaml leads to stackoverflow

### ISSUE THREAD

**Issue by MikeSchumacherCapgemini** [devonfw/tools-cobigen#578]
When trying to generate code from an OpenAPI document, if a component schema has a reference to another schema that has the first one as a parent, the parser loops indefinetly, creating a stackoverflow error.

**Comment by MikeSchumacherCapgemini** [comment]
@maybeec 
Adressed in #579, not sure if fixed

**Comment by maybeec** [comment]
@MikeSchumacherCapgemini we had this test you ignored for that issue. Can you enable it again?
As there is no PR anymore for openapiplugin it should now also not get any old builds

**Comment by MikeSchumacherCapgemini** [comment]
@maybeec the test is not ignored anymore since the latest commit
