### ISSUE TITLE
optimistic lock exception on double update of the same row

### ISSUE THREAD

**Issue by TobiaZambon** [devonfw/tools-cobigen#669]
Hi all, we have used devon + cobigen to generate several restfull CRUD services. We are facing issues due to OptimisticLock exceptions if we try to update twice the same record. We see that, when we call the first update, the service returns the updated entity but the modificationCounter have not been incremented and this leads to the issue when we call the save service the second time. How can we fix it? thanks!

**Comment by jdiazgon** [comment]
Closing issue because this is already fixed.

For solving it, we added `modificationCounter++` on one of our templates. See [this Pull Request](https://github.com/devonfw/tools-cobigen/pull/670).
