### ISSUE TITLE
Automatic updates of CobiGen templates

### ISSUE THREAD

**Issue by krashah** [devonfw/tools-cobigen#674]
Automatically update CobiGen templates inside Eclipse on click of some button/option.

**Comment by maybeec** [comment]
Some brainstorming for requirements elicitation and discussion:

* We should provide templates on the level of increments. Each increment will be downloaded on demand.
* On demand of the user, CobiGen can check for new versions of the increments cached on the local file system at first use.
* Tempaltes and its configuration are not visible to the user until he decides to adapt templates.
* If he decides to adapt an increment, a new standard `cobigen-config` project is created in the workspace and the increment to be added is extracted into the project, which can be adapted by the user.
* CobiGen will prefer user adapted templates over cached original ones.
* Adapted templates cannot be automatically updated.

More to the vision of increments:

* increments should be former understood as patterns, more specifically architecture implementation patterns (AIM patterns).
* an AIM pattern provides additional description, forces, etc. and serves as architecture documentation combined with a reference implementation specified by templates.

**Comment by krashah** [comment]
One idea is adding "Update Templates" option for CobiGen_Templates project only. 

Right click on CobiGen_Templates inside eclipse >CobiGen > Update Templates.

That will open one dialog where we can show 3 columns Name of Template, Current Version and latest version on Git.

We can provide button "Update Templates" to update all the templates in one go or update separately. This will update templates available in "\workspaces\main\CobiGen_Templates".

**Comment by maybeec** [comment]
How would you try to detect changes in the templates? This would imply saving all hashes of any version of every template on a server or a database to be queried by the client. Otherwise, you will leave the decision completely to the user and he might accidentially overwrite the templates?

**Comment by krashah** [comment]
My idea was to get latest git releases details of any plugin and then compare the version with the one in workspace. Need to check if it is possible.

**Comment by jdiazgon** [comment]
> How would you try to detect changes in the templates? 

It seems that Github provides like an API for getting the latest commits and its changes, see [this](https://developer.github.com/v3/repos/commits/). There is a response that states which files have been changed: 

```json 
"files": [
    {
      "filename": "file1.txt",
      "additions": 10,
      "deletions": 2,
      "changes": 12,
      "status": "modified",
      "raw_url": "https://github.com/octocat/Hello-World/raw/7ca483543807a51b6079e54ac4cc392bc29ae284/file1.txt",
      "blob_url": "https://github.com/octocat/Hello-World/blob/7ca483543807a51b6079e54ac4cc392bc29ae284/file1.txt",
      "patch": "@@ -29,7 +29,7 @@\n....."
    }
  ]
```

**Comment by maybeec** [comment]
and how to compare to the current version? Maintaining hashes? String compare would be highly non-efficient!
