### ISSUE TITLE
Adding button "Update templates" inside CobiGen menu parallel to "Health checkup" and "Generate"

### ISSUE THREAD

**Issue by krashah** [devonfw/tools-cobigen#683]
Our objective is to allow user to update and adapt the CobiGen templates whenever he needs. In this issue we will perform two tasks:

- [ ] Create button "Update templates" and on click of that allow user to install new templates from Maven Repository. We will store this downloaded templates to other location (Need to discuss)

- [ ] On click of "Generate" button, if CobiGen_Templates project is not imported then ask user to update it and then show already existing warning message.

Related/Dependent Issues

Part of issue #674

**Comment by maybeec** [comment]
Nearly fine, we for the second point, I understood following to hold:

* the user clicks on `generate`
* if there is a CobiGen_Templates folder in place, CobiGen Eclipse will take that up and start the dialog
* if no CobiGen_Templates project exists, it will ask the user to download the latest version from maven central of the templates (it might be necessary currently to ask which template set to download)
* it will store the latest version of the templates on the file system (maybe within the .metadata?)
* it will use the downloaded jar as configuration for generation
* if the user declines to download the templates, the error message is shown is it would have been shown before.
