### ISSUE TITLE
Adding button "Adapt templates" inside CobiGen menu parallel to "Health checkup"

### ISSUE THREAD

**Issue by krashah** [devonfw/tools-cobigen#684]
Our objective is to allow user to update and adapt the CobiGen templates whenever he needs. In this issue we will perform below task:

- [ ]  Create button "Adapt templates". This option will ask user to adapt the templates which was downloaded from "Update templates" inside CobiGen_Templates project. User should agree to overwrite the changes done by him inside templates. Once he agrees, we will update the latest templates inside the project. 

Related/Dependent Issues

Part of issue #674 and #683

**Comment by jdiazgon** [comment]
>User should agree to overwrite the changes done by him inside templates. Once he agrees, we will update the latest templates inside the project.

I was thinking that maybe we should disable button _"Adapt templates"_ if the CobiGen_Templates folder is already present.

Because the user is already able to adapt them (he has them on his workspace) and if he needs the latest templates, he can simply click on _"Update Templates"_

The rest seems fine to me :)

**Comment by maybeec** [comment]
> I was thinking that maybe we should disable button "Adapt templates" if the CobiGen_Templates folder is already present.

sign.

> Because the user is already able to adapt them (he has them on his workspace) and if he needs the latest templates, he can simply click on "Update Templates"

yes but basically, he should then get a message, that updating a folder is not possible. If he did not adapt anything, he can remove the project from the workspace to get the latest templates by download.

**Comment by krashah** [comment]
#674 and #683

**Comment by krashah** [comment]
#683
