### ISSUE TITLE
Evaluate nested java server app templates as of redundancy

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#687]
It seems that the oasp4j template folder crud_nested_java_server_app comes with redundant implementations also generated in the general crud_java_server_app. Both enable the search for Cto's, but is there any difference?

Please investigate whether the functionalty generated is really redundant and if so, lets discuss whether we want to keep it strongly separated or move everything together.

**Comment by maybeec** [comment]
@sjimenez77  @jdiazgon 
I found that issue when doing the JumpTheQueue tutorial.
In https://github.com/oasp/oasp-tutorial-sources/wiki/OASP4jAddingCustomFunctionality#list-visitors-with-their-access-code it says to add the Cto service, but it is already there. If we fix the templates to any direction, we should also check the tutorial.

**Comment by jdiazgon** [comment]
I see some differences on the code. For instance, `${variables.component#cap_first}SoapServiceImpl.java.ftl` makes use of CTos on the _crud_nested_java_server_app_ folder.

![image](https://user-images.githubusercontent.com/31688036/42091825-19ba9d7c-7ba7-11e8-8620-90ec807be779.png)

**Comment by maybeec** [comment]
It seems, that the nested rest interface does not generate anything in addition.

**Comment by maybeec** [comment]
I think it is fine to keep that separated as you not always want to have cto services.
We should refactor it for both SOAP and REST to behave the same.
I would even rename the increments to not "Nested REST" but maybe better "Cto REST Service".

**Comment by jdiazgon** [comment]
Already addressed with the release of templates-devon4j.
