### ISSUE TITLE
Error "Content is not allowed in prolog"

### ISSUE THREAD

**Issue by Hellmy** [devonfw/tools-cobigen#713]
### Expected behavior

As a cobigen user, I want helpful error messages so that I can track down an error and fix it.

### Actual behavior

Have a nearly bare project which generates a nearly empty file outputs following error message:
```
[...]
[Fatal Error] AttributeIndexDO.java:1:1: Content is not allowed in prolog.
[...]
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Haven following maven config
```xml
[...]
            <plugin>
                <groupId>com.capgemini</groupId>
                <artifactId>cobigen-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>generate</id>
                        <phase>package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <inputFiles>
                        <inputFile>src/main/java/attributevalue/entity/AttributeIndexDO.java</inputFile>
                    </inputFiles>
                    <increments>
                        <increment>bar</increment>
                    </increments>
                    <configurationFolder>../config/cobigen</configurationFolder>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.capgemini</groupId>
                        <artifactId>cobigen-tempeng-freemarker</artifactId>
                        <version>1.0.1</version>
                    </dependency>
                    <dependency>
                        <groupId>com.capgemini</groupId>
                        <artifactId>cobigen-javaplugin</artifactId>
                        <version>1.6.1</version>
                    </dependency>
                </dependencies>
            </plugin>
[...]
```
2. Have an nearly empty context.xml
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<contextConfiguration xmlns="http://capgemini.com/devonfw/cobigen/ContextConfiguration"
                      version="2.1">
    <trigger id="temp" type="java" templateFolder="temp">
        <containerMatcher type="package" value="((.+\.)\.entity"
                          retrieveObjectsRecursively="false"/>
        <matcher type="fqn" value="((.+\.)?([^\.]+))\.([^\.]+)\.entity\.([^\.]+)DO">
            <variableAssignment type="regex" key="rootPackage" value="1"/>
        </matcher>
    </trigger>
</contextConfiguration>
```
3. Have a nearly empty template.xml
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<templatesConfiguration xmlns="http://capgemini.com/devonfw/cobigen/TemplatesConfiguration"
                        version="2.1">

    <templateScans>
        <templateScan templatePath="templates" destinationPath="foo"/>
    </templateScans>
    <increments>
        <increment name="bar" description="bar">
            <templateRef ref="foo"/>
        </increment>
    </increments>
</templatesConfiguration>
```
4. Have nearly empty foo.ftl
```
foobar
```
5. `mvn package:generate` builds but also gives the error `[Fatal Error] AttributeIndexDO.java:1:1: Content is not allowed in prolog.`

**Comment by jdiazgon** [comment]
Hi Hellmy, thanks for your issue. It seems that you forgot to add the last part of your comment:

> mvn package:generate gives an...

Can you please update your comment with the content? Thanks.

**Comment by jdiazgon** [comment]
After some review, it seems that this `Content is not allowed in prolog` error shows up when either the workspace is corrupted or the xml files (like templates.xml or context.xml) contain some invalid characters.

I agree that we should provide helpful error messages and will do as soon as possible.

**Comment by maybeec** [comment]
@Hellmy Did I get you right? That the generation simply worked out, but you just reported the strange error message `1:1: Content is not allowed in prolog.` in the log?

**Comment by Hellmy** [comment]
Yes.


But it think I had the same error message during my first attempts to generate something... Perhaps I 
Nevertheless is the error message strange

**Comment by maybeec** [comment]
You are right. The error message is occurring if trying to read a non-XML file with the XML reader. Unfortunately, we cannot disable this logged message as it is logged out to system.out by the Java DOM parser.

Currently, we are trying to read any file with the different plugins installed as we cannot know the contents of the file. You could argue to "just use the file ending to determine the parser to be used". In general, this is ok, but we cannot provide a language/parser complete solution here, as XML, JSON, YAML are languages, which are used in multiple files. 

We could provide a heuristic like implementation in future to give hints to CobiGen, which parser to try first based on the file ending. Nevertheless, the error message might not vanish entirely in any case.
I opened a new issue for that purpose: #716

**Comment by Hellmy** [comment]
Sounds good to me, thank you
