### ISSUE TITLE
Improve reader performance by heuristically find the right plug-in to read an input

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#716]
### Expected behavior

As a user of CobiGen, I want to generate code based on a openAPI file without getting any errors in the log like `1:1: Content is not allowed in prolog.`

### Actual behavior

As we are trying to use all available parsers in a row to determine the language used in a file, the XML parser may be used before openAPI causing `1:1: Content is not allowed in prolog.` error messages if the file parsed is not of XML.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Take an openAPI file and start generating
2. See the red marked error log as stated above

### Related/Dependent Issues

#713 
#487

### Proposed Solution

Let us implement a heuristic, which enables parser selection based on the file ending. This would even improve performance. Therefore, we should introduce a new method in the InputReader API like 

```java
/**
 * Try to determine, whether the input file is readable by the plug-ins parser. If false is returned by the method, it is not assured, that the read method is not called at all. In case of the situation, that no plug-in is most likely to read the input, CobiGen will try every input reader to read the input. Please be aware, that this method should be kept highly performant. It does not have to be an exact result.
 * @return true, if it is most likely, that the file can be read by this input reader's read method<br>
 * false, if the reader is most likely not able to read the file. 
 */
boolean isMostLikelyReadable(Path path)`
```

The Java8 default implementation should return `false` to not introduce the necessity to adapt every plug-in after changing the `InputReader` interface.

**Comment by jdiazgon** [comment]
Issue is still showing up when running the CLI with a TypeScript file:

`[Fatal Error] 1:1: Content is not allowed in prolog`

One workaround is that `xml` input reading should be the last one to try. In class `InputInterpreterImpl` it could be very easy. We can change the key set and move `xml` to last position.

![image](https://user-images.githubusercontent.com/31688036/65582477-c6291d00-df7d-11e9-980d-7a04a3f68660.png)

**Comment by jdiazgon** [comment]
Another better solution is to use `isMostLikelyReadable` method from the same class (`InputInterpreterImpl `)
