### ISSUE TITLE
Two errors when using OpenAPI sample with Java

### ISSUE THREAD

**Issue by uhinze** [devonfw/tools-cobigen#762]
### Expected behavior

As a OpenAPI generator user, I want to generate the scaffold for my API in Java so that I save time in building up the boilerplates.

### Actual behavior
When generating from the usage wiki sample file, there are two kinds of errors:

#### 1
Entity class names are sometimes ambiguous. E.g. the class itself is called e.g. ShopSearchCriteriaTo, but there are references to ShopEntitySearchCriteriaTo which do not resolve and cause project errors. Same with ShopEntityEto vs. ShopEto.

On the other hand, some are fine, like SaleEto. I havent found out which makes one ok and the other not.

#### 2
Superfluous comments are causing syntax errors, e.g.:
```
  @Override
  public void /*
               * Generated value! You might want to set the operation name by operationId
               * (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-8) in the
               * openAPI definition
               */ postsale(ShopEntitySearchCriteriaTo criteria) {

    // TODO /* Generated value! You might want to set the operation name by operationId
    // (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-8) in the openAPI
    // definition */postsale
  }
```

Obviously only the second comment is meant to be put in.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Take the example swagger file from the usage documentation here: https://github.com/devonfw/tools-cobigen/wiki/cobigen-openapiplugin#full-example
2. Copy to root of project.
3. Take CobiGen_Templates from latest devonfw release package
4. Generate from Swagger

**Comment by uhinze** [comment]
Update: fixed the two errors with this patch, maybe you can use it. Seems like the references to the DAOs, which are called *Entity, are preserved:

```
From 7dbb4f6136df55a1d83abe0e9f63f8618481f6ea Mon Sep 17 00:00:00 2001
From: Ulrich Hinze <ulrich.hinze@capgemini.com>
Date: Fri, 28 Sep 2018 14:38:34 +0200
Subject: [PATCH] Fixed issues related to OpenAPI generation

---
 .../cobigen/templates/oasp4j/utils/OpenApiUtil.java        | 7 +++----
 1 file changed, 3 insertions(+), 4 deletions(-)

diff --git a/src/main/java/com/devonfw/cobigen/templates/oasp4j/utils/OpenApiUtil.java b/src/main/java/com/devonfw/cobigen/templates/oasp4j/utils/OpenApiUtil.java
index 37e0dee..a7f6ffc 100755
--- a/src/main/java/com/devonfw/cobigen/templates/oasp4j/utils/OpenApiUtil.java
+++ b/src/main/java/com/devonfw/cobigen/templates/oasp4j/utils/OpenApiUtil.java
@@ -166,12 +166,12 @@ public class OpenApiUtil {
 
         if (isCollection) {
             if (isEntity) {
-                return "List<" + parameter.get("type") + "Entity>";
+                return "List<" + parameter.get("type") + ">";
             } else {
                 return "List<" + typeConverted + ">";
             }
         } else if (isEntity) {
-            return (String) parameter.get("type") + "Entity";
+            return (String) parameter.get("type");
         }
         return typeConverted;
     }
@@ -195,8 +195,7 @@ public class OpenApiUtil {
             } else {
                 lastSegment = split[split.length - 2];
             }
-            return "/* Generated value! You might want to set the operation name by operationId (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-8) in the openAPI definition */"
-                + ((String) operation.get("type")) + lastSegment;
+            return ((String) operation.get("type")) + lastSegment;
         } else {
             return operationId;
         }
-- 
2.17.0


```


This does however remove the mentioned comments entirely.

**Comment by jdiazgon** [comment]
Hi Ulrich, thank you very much for creating this issue. I really appreciate that you already fixed it, I wish everyone did that 👍 

I will test it and see if it works for every case. Sometimes, the problem is that our developers forget to add the "Entity" at the end of their parameters name, so we need to provide a solution to that case.

Next time, it would be really nice if you could fork this repository and create a Pull Request with the solution. It is our normal way of working. Thanks!
