### ISSUE TITLE
Provide two templates sets: OASP4J and devon4j

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/tools-cobigen#769]
### Expected behavior

As a developer of devonfw, I want to have CobiGen templates for both OASP4J 3.0.0 and devon4j 3.0.0 so that I am able to generate correct templates for the version that I most prefer.

### Possible solutions

1.  We could provide two templates sets on the workspaces\main folder. One could be called _CobiGen_Templates_devon4j_ and the other _CobiGen_Templates_oasp4j_ so that our developer just has to import the ones that he needs. (maybe he wouldn't even need to rename as it is specified by the pom).

    1. **Drawbacks:** Our developers may get confused if they see two template sets. Also we would need to inform about this change to them

2. Provide both templates set in the same folder but with different increments, as similar to shown in below image, but instead of `devon4j 2.x.x` should be `oasp4j-3.0.0`
![image](https://user-images.githubusercontent.com/31688036/46529522-01c36680-c897-11e8-9844-08ddb8244133.png)
    1. **Drawbacks**; Loading more templates may result in performance issues. However, I think this is more intuitive for our developers.

### Related PRs

[devon4j#16](https://github.com/devonfw/devon4j/pull/18).

### Related issues
#751

**Comment by maybeec** [comment]
We should investigate the performance.
In general if there are a lot of increments it might even get hard to get an overview.

**Comment by jdiazgon** [comment]
Most probably this will be closed as some of us have decided to only provide templates compliant with devon4j 3.0.0.

**Comment by jdiazgon** [comment]
Closing as manager decision is to just provide devon4j templates.
