### ISSUE TITLE
Duplicated inheritance when the extension is a generic class

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/tools-cobigen#784]
### Expected behavior

Templates should be generated without any duplicated inheritance.

### Actual behavior

When a template `extends` a generic class, then the merger does not recognize properly this extension and duplicates it.

From:
``public interface SampleDataRepository extends DefaultRepository<SampleDataEntity> {``

To:

``public interface SampleDataRepository extends DefaultRepository<SampleDataEntity>, DefaultRepository<SampleDataEntity> {``

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. From a simple Java Entity, generate increment `CRUD Springdata repository`
2. Generate again the same increment and you will get the duplicated extension (compilation error)

**Comment by maybeec** [comment]
please check if this is the case as of different import statements of DefaultRepository in the base file and in the template. If the imports differ, this might be the effect you see.

**Comment by jdiazgon** [comment]
You are completely right, it was an old import the one messing everything up. 👍
