### ISSUE TITLE
Static and object initializers are removed on merge

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#791]
### Expected behavior

Merging new code into a java class should just add or replace the code generated.
It should not harm any other code.

### Actual behavior

static initializers like 

```java
static {
    IGNORE_CASE = new StringSearchConfigTo();
    IGNORE_CASE.setIgnoreCase(true);
  }
```

or object initializers like
```java
{
    IGNORE_CASE = new StringSearchConfigTo();
    IGNORE_CASE.setIgnoreCase(true);
  }
```

are removed after merging.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. create a class
```java
public class A {
private static int i;
static {
    i = 1;
  }
}
```

and create any template to generate code into the class like a new field or method and use any of the `javamerge` strategies.

**Comment by jdiazgon** [comment]
Already fixed
