### ISSUE TITLE
Feedback on search by criteria

### ISSUE THREAD

**Issue by hohwille** [devonfw/tools-cobigen#858]
I collected very valuable feedback from real-life devonfw projects:
* seach criteria generated code does not support to search inside embeddables
* search query logic for embeddables that are used in multiple entities would lead to redundancies. Hence they generated a *DaoHelper/*RepositoryHelper to centralize this code generated for the embeddable and use it on generation of entities that embed the embeddable
* the project had a very common demand: allow more flexible searches. So e.g. the user may not only search for a string but also with many different search operators including `in` what requires the search value for the according property to be a `List`.
* I have access to all the changes they did to the cobigen templates
* I have already reviewed these changes and would suggest to go for a more universal design. This means that for each data type we would create a search criteria object. This would contain the operator together with the value(s) to search for. According to the type only operators that make sense in that context would be possible. Generic super-classes allow reuse and a generic implementation can be used for custom datatypes to avoid the need to create costom implementations as well. This would imply some changes to devon4j (e.g. for 3.1.0).

IMHO a great enhancement of our generation portfolio.
WDYT?

**Comment by jdiazgon** [comment]
Seems interesting!

> I have access to all the changes they did to the cobigen templates

This would be really useful :)

>  This means that for each data type we would create a search criteria object. 

I don't get this part completely. With data type do you mean for example our `employee` or `user` entity? Isn't that what we currently have? We create a new `SearchCriteriaTo` object for each entity.

Maybe it would be easier when I see the code.

**Comment by hohwille** [comment]
> >  This means that for each data type we would create a search criteria object.
> 
> I don't get this part completely. With data type do you mean for example our employee or user entity?

For the meaning of "data type" read this:
https://m-m-m.github.io/maven/apidocs/net/sf/mmm/util/lang/api/Datatype.html

So what I am saying here is that we need something like `StringSearchCriteria`, `IntegerSearchCriteria`, `BooleanSearchCriteria`, `InstantSearchCriteria`, `LocalDateSearchCriteria`, etc.

Then the generated `FooSearchCriteriaTo` would not contain 
`private String myProperty`
(with according getters and setters) but instead 
`private StringSearchCriteria myProperty`

Then I could assign this to `StringSearchCriteria.isEqualTo("exact match")` but also to `StringSearchCriteria.isLike("*someInfix*")` or `StringSearchCriteria.isIn(true, "option1", "option2", "option3")` (where the first parameter is for case-sensitivity and the second is a String vararg). This API is just a draft as I would suggest it.

The even more important part is the JSON that would then change from
```
"myProperty": "exact match"
```
to something like:
```
"myProperty": {
  "op": "eq",
  "values": [ "exact match" ]
}
```

More clear now?

**Comment by jdiazgon** [comment]
Thanks for the explanation, much more clear now.

I agree that this feature adds more flexibility and would be interesting to add. However, I think that we should still allow JSON like:
```
"myProperty": "exact match"
```
IMHO most of the times you won't need operators like the ones you have shown with `"op" : "eq"`. In my opinion, we should still provide the possibility to use `searchCriteria` as before, like a "simple" way. Then, if the JSON is like:

```
"myProperty": {
  "op": "eq",
  "values": [ "exact match" ]
}
```

Of course our code would be able to understand it.

**Comment by hohwille** [comment]
IMHO your suggestion is adding complexity we can not solve easily with standard tools such as Jackson.
If you say `"myProperty": "exact match"` this implies that `myProperty` is a String by default where as with
```
"myProperty": {
  "op": "like",
  "values": [ "*infix*" ]
}
```
It will be a custom object. We can create custom serializers and deserializers to make this somehow possible but IMHO this will only cause problems and raise support questions as people will not understand what is going on. However, just my personal point of view. If others agree with you, I am fine to accept. I only learned from other such design decisions in the past that we should really clarify them and not "decide by accident or occasion".

**Comment by hohwille** [comment]
I created a preview experiment in keywi:
* https://github.com/hohwille/keywi/tree/feature/flatten-structure/api/src/main/java/com/devonfw/module/criteria/common/api/query
* https://github.com/hohwille/keywi/tree/feature/flatten-structure/core/src/main/java/com/devonfw/module/criteria/dataaccess/base/query

**Comment by hohwille** [comment]
Any Feedback? Should we add this to devon4j 3.1.0?
Any suggestions for improvements?

**Comment by jdiazgon** [comment]
This is a very interesting feature that we should add in the future. However, as the code freeze is on this Friday, I think we should not focus on this for the current release.
