### ISSUE TITLE
Generate OpenApi def. file from code

### ISSUE THREAD

**Issue by ckorbet** [devonfw/tools-cobigen#863]
### Expected behavior
As a developer, I want to be able to generate API definition file (OpenAPI) so that the API definition file can be more easily modified based on what's actually coded.

### Actual behavior
Cobigen generates code from API, but not the other way around

### Related/Dependent Issues
As possible solution, whenever Cobigen generates code from OpenApi file, the generated code could contain the appropriate Swagger/OpenApi Java annotations in the corresponding REST services/ETOs/CTOs, using swagger-core.

### E.g.:
```
@GET
  @Path("/{petId}")
  @Operation(summary = "Find pet by ID",
    tags = {"pets"},
    description = "Returns a pet when 0 < ID <= 10.  ID > 10 or nonintegers will simulate API error conditions",
    responses = {
            @ApiResponse(description = "The pet", content = @Content(
                    schema = @Schema(implementation = Pet.class)
            )),
            @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
            @ApiResponse(responseCode = "404", description = "Pet not found")
    }) 
```

**Comment by jdiazgon** [comment]
Thanks for the issue!

Interesting request, I think this could be easily implemented.
