### ISSUE TITLE
POM structure invalid

### ISSUE THREAD

**Issue by hohwille** [devonfw/tools-cobigen#921]
Actually you have a POM structure in your cobigen git repo that is broken.
The `artifactId` of this POM was changed from `cobigen-parent` to `parent` (for some odd reason, see blame):
https://github.com/devonfw/tools-cobigen/blob/dev_core/cobigen/pom.xml#L5
However, most of the children (modules) of this POM have never been updated accordingly and still refer to the old `cobigen-parent` artifactId in their parent section:
https://github.com/devonfw/tools-cobigen/blob/dev_core/cobigen/cobigen-htmlplugin/pom.xml#L11

Therefore the project can not be cloned from git and build with maven OOTB:
```
[ERROR] The build could not read 9 projects -> [Help 1]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-javaplugin-parent:dev-SNAPSHOT (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-javaplugin-parent/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-javaplugin-parent:dev-SNAPSHOT: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-xmlplugin:3.1.0 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-xmlplugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-xmlplugin:3.1.0: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-propertyplugin:1.2.0 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-propertyplugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-propertyplugin:1.2.0: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-textmerger:1.2.0 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-textmerger/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-textmerger:1.2.0: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-jsonplugin:1.2.0 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-jsonplugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-jsonplugin:1.2.0: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-htmlplugin:1.1.0 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-htmlplugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-htmlplugin:1.1.0: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-tsplugin:1.1.1 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-tsplugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-tsplugin:1.1.1: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-openapiplugin:1.1.0 (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-openapiplugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-openapiplugin:1.1.0: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project com.capgemini:cobigen-tempeng-parent:dev-SNAPSHOT (/projects/devon/workspaces/cobigen/cobigen/cobigen/cobigen-templateengines/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capgemini:cobigen-tempeng-parent:dev-SNAPSHOT: Could not find artifact com.capgemini:cobigen-parent:pom:dev-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11 -> [Help 2]
```

This is really giving contributors a hard time. Also you are violation some naming conventions and best-practices of maven.

Why dont you get this error?
Most probably because you have a `settings.xml` with an external repository configured that is still containing the `cobigen-parent` POM (the devon PL nexus).

To be honest and straight away:
I think the entire setup with branches and maven structure should be revisited as it is very uncommon and inconvenient. I would recommend to either:
* really consider spliting this up into different products (plugins) each with its own Git Repo and maven structure
* or simply giving up this overcomplicated approach and follow the feature and PR based approach of continuous improvement we use in any other repo of devonfw what IMHO would also work fine for cobigen.

You may of course have your own oppinion and maybe also I am missing something, but even to me it is sometimes helpful if someone is giving me a harsh PoV to rethink my own view. So take it or leave it, but please fix your POMs so they are valid.

**Comment by hohwille** [comment]
If I am not mistaken you also do not have CI (travis) in place for cobigen. We have increased our process quality immense by strictly working with only PRs and having CI for every change. I know that osgi is tricky but IMHO your build could still work in travis or you could disable some tricky parts of the build only for CI to make things work.

**Comment by hohwille** [comment]
See also:
https://github.com/devonfw/tools-cobigen/blame/dev_core/cobigen/pom.xml
and
https://github.com/devonfw/tools-cobigen/blame/faad85d102b161a4660f3af7d879afaf92dfda10/cobigen/pom.xml

**Comment by jdiazgon** [comment]
> If I am not mistaken you also do not have CI (travis) in place for cobigen

You are right. We did try to use Travis in CobiGen, but we were facing some build issues which I don't correctly remember. That's why we decided to remove it.

Anyway we should try Travis again.

**Comment by maybeec** [comment]
@hohwille we are blocked here currently as we are using the PL internal nexus and p2 deployment. If this is all used on public providers we can start using travis.

Regarding the issue. I agree from what I read here, thanks for the hint. We should fix it asap.

**Comment by hohwille** [comment]
I assume this is a bug:
https://github.com/devonfw/tools-cobigen/blob/eeb0eb1d105823f1ec33f545059e0d4d55f8d86e/cobigen/cobigen-core-parent/pom.xml#L10

Will create a PR for it asap as this is blocking me for further contribution...

**Comment by hohwille** [comment]
OK. I was wrong there is more odd here.
The problem actually is that the plugins in core reference this parent:
```
  <parent>
    <groupId>com.capgemini</groupId>
    <artifactId>cobigen-parent</artifactId>
    <version>dev-SNAPSHOT</version>
  </parent>
```
However, this parent does not exist on the same branch.
What should be the actual parent of these plugins?
The natural answer would be:
```
  <parent>
    <groupId>com.devonfw.cobigen</groupId>
    <artifactId>parent</artifactId>
    <version>dev-SNAPSHOT</version>
  </parent>
```
Could I do that change and provide a PR for it, or is that still wrong?

IMHO you are violating various maven conventions and best-practices what is making it not so easy to see what should be the "truth".

**Comment by maybeec** [comment]
Could you give a pointer? I hardly doubt, that there is a reference to com.capgemini left. I could not find it directly.

**Comment by hohwille** [comment]
Something is playing tricks on me:
https://github.com/devonfw/tools-cobigen/blob/dev_core/cobigen/cobigen-javaplugin-parent/pom.xml
However, in my unchaged fork, I have this content for the same pom:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.capgemini</groupId>
  <artifactId>cobigen-javaplugin-parent</artifactId>
  <version>dev-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>CobiGen Javaplugin Parent</name>

  <parent>
    <groupId>com.capgemini</groupId>
    <artifactId>cobigen-parent</artifactId>
    <version>dev-SNAPSHOT</version>
  </parent>

  <modules>
    <module>cobigen-javaplugin</module>
    <module>cobigen-javaplugin-model</module>
  </modules>

</project>
```

**Comment by hohwille** [comment]
I will once more delete my fork and create it from scratch.

**Comment by hohwille** [comment]
Seems you did some changes to `dev_core` as it is now working.
I just found the commit from you one hour ago:
https://github.com/devonfw/tools-cobigen/commit/e671401f67443683e1707cf5c670a7f04ab6978f
That is fixing the problems I was talking about.
So thanks for the fixes. I can work now.
Maybe we can also discuss your branching stratgegy in CobiGen to simplify and avoid such problems.

**Comment by hohwille** [comment]
The actual issue "POM structure invalid" is now fixed, hence I am closing this.

However regarding my points to improve maven structure, conventions, best-practices and also the branching strategy, I would be happy to stay in contact and get some improvements on its way.
