### ISSUE TITLE
TBD feature request for indendation (edge case?)

### ISSUE THREAD

**Issue by hohwille** [devonfw/tools-cobigen#954]
As a CobiGen template developer I also want to be able to generate (flyway) SQLs. We have requirements and conventions for formatting SQLs that imply that column types are indented such that they are aligned.
So instead of:
```
CREATE TABLE TABLE_NAME(
  ID DECIMAL(10,0),
  VERSION INTEGER NOT NULL,
  TITLE  VARCHAR2(255 CHAR),
  ...
)
```
it should be:
```
CREATE TABLE TABLE_NAME(
  ID         DECIMAL(10,0),
  VERSION    INTEGER NOT NULL,
  TITLE      VARCHAR2(255 CHAR),
  ...
)
```
I know this is an absolute edge-case. Currently I have no clue how I could solve this with CobiGen. I am also fine if we reject this issue and say that CobiGen should not address formatting of structured types at all and that should be handled with other tools (Eclipse, etc.).

Anyhow, I just wanted to bring up such a demand so we can discuss and think further. Might be also interesting to think about formatting in the case of language agnostic templates (see #158).

**Comment by hohwille** [comment]
If we would not want to reject this issue we could offer a syntax to fill up with spaces until a given column is reached (maybe this is even possible with freemarker or velocity but I am not aware of it).

**Comment by jdiazgon** [comment]
There is actually something in Freemarker that may help you: [right_pad](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_right_pad)

The following template:
```
CREATE TABLE TABLE_NAME(
  ${"ID"?right_pad(15)}DECIMAL(10,0),
  ${"VERSION"?right_pad(15)}INTEGER NOT NULL,
  ${"TITLE"?right_pad(15)}VARCHAR2(255 CHAR),
  ...
)
```

Prints:
```
CREATE TABLE TABLE_NAME(
  ID             DECIMAL(10,0),
  VERSION        INTEGER NOT NULL,
  TITLE          VARCHAR2(255 CHAR),
  ...
)
```

**Comment by hohwille** [comment]
Cool. I will try that. I assume we can close this issue then. Thanks for pointing out.
