### ISSUE TITLE
cobigen not compatible with jdk >9

### ISSUE THREAD

**Issue by maybeec** [devonfw/tools-cobigen#970]
### Expected behavior
As a user I want to do a health check also when running my eclipse with jdk 9 and newer

### Actual behavior
for example the advanced health check is failing as of jaxb classes not found.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install cobigen in an eclipse an run eclipse with java 11
2. right click in package or project explorer and choose cobigen -> health check
3. choose advanced health check in the upcoming health check popup 

### Related/Dependent Issues
devonfw/devon-ide#84

**Comment by jdiazgon** [comment]
Unfortunately, our CobiGen CLI is also not compatible with JDK > 9. There have been [major changes](https://community.oracle.com/thread/4011800) on the jar classpath loading.

I hope I will find easy solutions.

**Comment by jdiazgon** [comment]
Fixed with #1026 #1025 #1024
